### ISSUE TITLE
very small emblems in list view

### ISSUE THREAD

**Issue by qrpyr** [chrisjbillington/git_nautilus_icons#21]
This is only about list view:

- In the smallest zoom level (50%), multiple emblems are displayed, but they are barely visible
- In the second zoom level (100%), only one emblem is shown, the size is okay
- From the third zoom level on (150% +), multiple emblems are displayed, size is okay

![icons](https://user-images.githubusercontent.com/6173040/143545596-bcc74ef7-2b9c-416a-ab74-585c76b93d2e.png)

Is it possible to change in the smalles zoom level the number of emblems displayed and the size of the emblem?
I tried the icon index file as suggested in #13, but it did not work for me.

Thank you for the plugin and for reading this!

**Comment by chrisjbillington** [comment]
Hi! Thanks for the kind words on the plugin :)

I have attempted to do what I can to make there be simplified icons at very small sizes, but unfortunately this requires a change in the freedesktop hicolor icon theme project to work correctly. I have made a pull request with the required changes, but it has not been merged yet. There are instructions in the README of this project for how you can make this work on your system here:

https://github.com/chrisjbillington/git-nautilus-icons#simplified-icons-at-small-sizes

If you follow the instructions in the README, does that work? It should be the same as the changes in the pull request you linked, but copying the `index.theme` from the pull request will ensure you haven't made any errors manually making the required changes.

If that does not work (you might want to restart nautilus: `killall nautilus` to make sure), then let me know what OS you're using, perhaps I can reproduce the problem.

**Comment by qrpyr** [comment]
Thanks for the swift response!

My OS is Arch Linux, the installed packages/versions:
[nautilus 41.1-1](https://archlinux.org/packages/extra/x86_64/nautilus/)
[python-nautilus 1.2.3-5](https://archlinux.org/packages/community/x86_64/python-nautilus/)
[git-nautilus-icons 2.0.2-1](https://aur.archlinux.org/packages/git-nautilus-icons)
i also tried [git-nautilus-icons-git](https://aur.archlinux.org/packages/git-nautilus-icons-git)

I replaced the index file and killed all nautilus processes, still no effect in the lowest zoom level.

However, something different: just noticed that when nautilus is initially (after killing all processes) started from the terminal, and then I press `Ctrl-C` I get the following error message, but nautilus refuses to close.

```python
^CTraceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/git-nautilus-icons.py", line 802, in <module>
    worker.run()
  File "/usr/share/nautilus-python/extensions/git-nautilus-icons.py", line 679, in run
    if self.conn.poll(timeout):
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 262, in poll
    return self._poll(timeout)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 429, in _poll
    r = wait([self], timeout)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 936, in wait
    ready = selector.select(timeout)
  File "/usr/lib/python3.9/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
^C^C^C^C^C^C
```

**Comment by chrisjbillington** [comment]
I'm on Arch too, will see if I can reproduce the problem.

The keyboard interrupt is unrelated and pretty unavoidable - git-nautilus-icons launches a worker subprocess, and your terminal decides to give the subprocess the ctrl-c keyboard input for some reason. Not something worth thinking too much about!

**Comment by stevenxxiu** [comment]
On *Arch Linux*, on the latest *Nemo* commit <https://github.com/linuxmint/nemo/commit/f2ee70790057a1639527858a2c9a232c3b8a3688> and the latest update of this to v2.2.0, I'm getting this issue again. I'm not really sure what happened. Can you reproduce this?

**Comment by chrisjbillington** [comment]
Ah, very annoying.

Try updating to the latest AUR package now @stevenxxiu.

I had removed the smallest icons from that package because current nautilus *only* uses small ones, which means it never shows any detailed icons at all. So I was forcing it to use the scalable ones by removing the smallest non-scalable ones. 

I'll have to figure out how to thread that needle - ideally nautilus would use appropriately sized icons for the current zoom level instead of fixed-sized ones. But reverted to previous behaviour for now until I figure something out.
